import { Version } from '../model/version';

export const VERSIONS: Version[] = [
    { id: 1, idAppli: 'NAP', versionAppli: '0230C', idEngine: 'dialogue_9_0_110', versionLivraison: 'AUTRE',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 2, idAppli: 'NAP', versionAppli: '0240D', idEngine: 'dialogue_7_0_611', versionLivraison: 'L1410',
            dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 3, idAppli: 'NAP', versionAppli: '0240E', idEngine: 'dialogue_9_0_110', versionLivraison: 'AUTRE',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 4, idAppli: 'NAP', versionAppli: '0240C', idEngine: 'dialogue_9_0_110', versionLivraison: 'AUTRE',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 5, idAppli: 'NAP', versionAppli: '0100', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 6, idAppli: 'NAP', versionAppli: 'DEV', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 7, idAppli: 'NAP', versionAppli: 'DEV0100', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },

    { id: 8, idAppli: 'SAGA', versionAppli: '0100', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 9, idAppli: 'SAGA', versionAppli: 'DEV', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 10, idAppli: 'SAGA', versionAppli: 'DEV0100', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 11, idAppli: 'SAGA', versionAppli: '0300', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: 'didsg304', dernierLivrableJ2ee: '' },
    { id: 12, idAppli: 'SAGA', versionAppli: 'DEV0300', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 13, idAppli: 'SAGA', versionAppli: '7000', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 14, idAppli: 'SAGA', versionAppli: 'DEV7000', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },

    { id: 15, idAppli: 'NSF', versionAppli: '0200', idEngine: 'dialogue_8_0_319', versionLivraison: 'L1410',
        dernierLivrable: 'didsf203', dernierLivrableJ2ee: '' },
    { id: 16, idAppli: 'NSF', versionAppli: '0100', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 17, idAppli: 'NSF', versionAppli: 'DEV0100', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 18, idAppli: 'NSF', versionAppli: '0108', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 19, idAppli: 'NSF', versionAppli: 'DEV0108', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 20, idAppli: 'NSF', versionAppli: '7000', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 21, idAppli: 'NSF', versionAppli: 'DEV7000', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },

    { id: 22, idAppli: 'CRI', versionAppli: '3600', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 23, idAppli: 'CRI', versionAppli: '370', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 24, idAppli: 'CRI', versionAppli: '3700', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 25, idAppli: 'CRI', versionAppli: '380', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 26, idAppli: 'CRI', versionAppli: '3800', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 27, idAppli: 'CRI', versionAppli: '3900', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 28, idAppli: 'CRI', versionAppli: '4000', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },

    { id: 29, idAppli: 'MAGIC', versionAppli: '08100', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 30, idAppli: 'MAGIC', versionAppli: '08110', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 31, idAppli: 'MAGIC', versionAppli: '08200', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 32, idAppli: 'MAGIC', versionAppli: '08210', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 33, idAppli: 'MAGIC', versionAppli: '09000', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 34, idAppli: 'MAGIC', versionAppli: 'DEV08100', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 35, idAppli: 'MAGIC', versionAppli: 'DEV09000', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },

    { id: 36, idAppli: 'CSP', versionAppli: '7000', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 37, idAppli: 'CSP', versionAppli: 'DEV7000', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 38, idAppli: 'CSP', versionAppli: '8000', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 39, idAppli: 'CSP', versionAppli: 'DEV8000', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 40, idAppli: 'CSP', versionAppli: '0300', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 41, idAppli: 'CSP', versionAppli: 'DEV0300', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 42, idAppli: 'CSP', versionAppli: 'N190', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },

    { id: 43, idAppli: 'NPJ', versionAppli: '7000', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 44, idAppli: 'NPJ', versionAppli: 'DEV7000', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 45, idAppli: 'NPJ', versionAppli: '8000', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 46, idAppli: 'NPJ', versionAppli: 'DEV8000', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 47, idAppli: 'NPJ', versionAppli: '0200', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 48, idAppli: 'NPJ', versionAppli: 'DEV0200', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },

    { id: 49, idAppli: 'IDEAL', versionAppli: '0100', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 50, idAppli: 'IDEAL', versionAppli: '0160', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 51, idAppli: 'IDEAL', versionAppli: 'DEV0100', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 52, idAppli: 'IDEAL', versionAppli: 'DEV0160', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 53, idAppli: 'IDEAL', versionAppli: '0170', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 54, idAppli: 'IDEAL', versionAppli: '0180', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },

    { id: 55, idAppli: 'ECC', versionAppli: '7000', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 56, idAppli: 'ECC', versionAppli: 'DEV7000', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 57, idAppli: 'ECC', versionAppli: '8000', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 58, idAppli: 'ECC', versionAppli: 'DEV8000', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 59, idAppli: 'ECC', versionAppli: '0100', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: 'didec001', dernierLivrableJ2ee: '' },
    { id: 60, idAppli: 'ECC', versionAppli: 'DEV0100', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },

    { id: 61, idAppli: 'MUTI', versionAppli: '0200', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 62, idAppli: 'MUTI', versionAppli: 'DEV0200', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 63, idAppli: 'MUTI', versionAppli: 'DEV4000', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 64, idAppli: 'MUTI', versionAppli: '4000', idEngine: 'dialogue_8_0_319', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 65, idAppli: 'MUTI', versionAppli: '0100', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' },
    { id: 66, idAppli: 'MUTI', versionAppli: '3700', idEngine: 'dialogue_7_0_611', versionLivraison: '',
        dernierLivrable: '', dernierLivrableJ2ee: '' }
];
